version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_vue_nginx
    working_dir: /var/www/html
    ports:
      - 7000:80
    volumes:
      - ./:/var/www/html
      - ./.docker/server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel_vue_template

  mysql:
    image: mysql:5.7.22
    container_name: laravel_vue_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    volumes:
      - ./.docker/.database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_vue_template
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel_vue_template

  php:
    build:
      context: .
    container_name: laravel_vue_php
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel_vue_template

  composer:
    image: composer:latest
    container_name: laravel_vue_composer
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_vue_template
  
  artisan:
    build:
      context: .
    container_name: laravel_vue_artisan
    entrypoint: ['/var/www/html/artisan']
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_vue_template

  yarn:
    image: node:14.15
    container_name: yarn
    entrypoint: ['yarn']
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_vue_template

networks:
  laravel_vue_template:
