version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/html
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel_vue_template

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - laravel_vue_template

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel_vue_template

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_vue_template
  
  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: artisan
    entrypoint: ['/var/www/html/artisan']
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_vue_template

  yarn:
    image: node:14.15
    container_name: yarn
    entrypoint: ['yarn']
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_vue_template

networks:
  laravel_vue_template:
